import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'en' | 'es';

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.assessment': 'Assessment',
    'nav.services': 'Services',
    'nav.instagram': 'Instagram',
    'nav.booking': 'Booking',
    'nav.contact': 'Contact',
    'nav.cta': 'Book a Session',

    'hero.subtitle': 'Holistic Therapist',
    'hero.tagline': 'Expand your energy.\nHeal your roots.\nLive fully.',
    'hero.badge': 'Holistic Healing',
    'hero.h1.1': 'Restore Your',
    'hero.h1.accent': 'Balance',
    'hero.h1.2': 'Body, Energy & Spirit',
    'hero.quote': 'Healing is a journey, not a destination.',
    'hero.description': 'Sacred sound, energy work, and intuitive healing to restore balance and awaken your highest potential.',
    'hero.cta.primary': 'Begin Your Journey',
    'hero.cta.secondary': 'Explore Services',
    'hero.scroll': 'Scroll to explore',

    'about.label': 'The Healer',
    'about.meet': 'Meet',
    'about.title': 'A guide back\nto yourself',
    'about.p1': 'I\'m Maca Salvo — a holistic therapist blending ancestral wisdom with modern energy practices to support deep transformation.',
    'about.p2': 'My path began with my own healing journey, navigating anxiety, disconnection, and the search for deeper meaning. That path led me to discover the profound power of sound, energy, and sacred ritual.',
    'about.p3': 'Today I hold space for those ready to peel back the layers — to reconnect with their body\'s intelligence, release what no longer serves, and step into their fullest expression.',
    'about.certifications': 'Certifications & Training',
    'about.cert1': 'Certified Sound Healing Practitioner',
    'about.cert2': 'Access Bars Facilitator',
    'about.cert3': 'Sacred Geometry & Karnak Pendulum',
    'about.cert4': 'Reiki Master Level III',
    'about.cert5': 'Theta Healing Practitioner',
    'about.cta': 'Schedule a Session',
    'about.stat1.value': '500+',
    'about.stat1.label': 'Lives Touched',
    'about.stat2.value': '8+',
    'about.stat2.label': 'Years of Practice',
    'about.stat3.value': '12',
    'about.stat3.label': 'Modalities',
    'about.journey.label': 'My Journey',
    'about.journey.title': 'A Path of Awakening',
    'about.journey.text': 'It began with a quiet restlessness — a sense that there was something deeper waiting to be found. That feeling became the beginning of everything.\n\nI dove into holistic therapies and energy practices, not as a student, but as someone searching for herself. Every modality I encountered left a mark.\n\nI trained and certified as a holistic therapist to offer what had transformed my own life: a grounded, loving space to heal.\n\nToday I walk beside others on their path — helping them release, realign, and reconnect with the wisdom they have always carried within.',
    'about.philosophy.label': 'My Philosophy',
    'about.philosophy.title': 'Life as a Process of Expansion and Reconnection',
    'about.philosophy.text': 'I believe in a path of conscious living, where every experience has a purpose and invites us to return to ourselves.\n\nFor me, healing is not a destination, but a process of constant reconnection with the body, the mind, the energy, and the essence. A remembering of who we are beyond what we have learned, what has been conditioned in us, and what we have carried for years.\n\nI work from the idea that everything is in constant movement: our emotions, our energy, and our vibration. When we learn to observe ourselves with presence and love, we begin to generate internal spaces of balance and real transformation.\n\nI believe deeply in the intelligence of the body and in the inner wisdom that each person holds to guide their own process. My role is to accompany, hold space, and facilitate environments where that can emerge with greater clarity.\n\nEvery encounter is an invitation to return to inner coherence, to release what weighs us down, and to open space for a more aligned and conscious version of ourselves.\n\nI also believe that healing is not linear — it has its own rhythm, its own pauses, and its own leaps forward. Honoring that process, without forcing it, is at the heart of everything I do.',
    'about.approach.label': 'My Approach',
    'about.approach.title': 'An Intentional, Personalized Space',
    'about.explore': 'Explore My Services',
    'about.years': 'Years',
    'about.value1.label': 'Compassion',
    'about.value1.desc': 'Every session begins with deep listening and an open heart.',
    'about.value2.label': 'Natural Healing',
    'about.value2.desc': 'Harnessing ancient wisdom and natural energetic practices.',
    'about.value3.label': 'Sacred Space',
    'about.value3.desc': 'Creating intentional environments for transformation to unfold.',
    'about.value4.label': 'Empowerment',
    'about.value4.desc': 'Guiding you to rediscover your own inner light and strength.',

    'assessment.label': 'Self Discovery',
    'assessment.title': 'Where does your\nhealing begin?',
    'assessment.subtitle': 'Answer a few questions to discover which healing modality aligns most with your current needs.',
    'assessment.step': 'Step',
    'assessment.of': 'of',
    'assessment.complete': '% Complete',
    'assessment.q1': 'What can we help you with?',
    'assessment.q1.anxiety.label': 'Anxiety',
    'assessment.q1.anxiety.desc': 'Persistent worry, racing thoughts, tension',
    'assessment.q1.depression.label': 'Depression',
    'assessment.q1.depression.desc': 'Low mood, lack of motivation, emptiness',
    'assessment.q1.relationships.label': 'Relationship Issues',
    'assessment.q1.relationships.desc': 'Patterns, communication, connection',
    'assessment.q1.transitions.label': 'Life Transitions',
    'assessment.q1.transitions.desc': 'Major changes, new chapters, uncertainty',
    'assessment.q1.grief.label': 'Grief & Loss',
    'assessment.q1.grief.desc': 'Processing endings, mourning, acceptance',
    'assessment.q1.stress.label': 'Stress Management',
    'assessment.q1.stress.desc': 'Overwhelm, burnout, depletion',
    'assessment.q1.selfesteem.label': 'Self-Esteem',
    'assessment.q1.selfesteem.desc': 'Self-worth, confidence, inner voice',
    'assessment.q1.trauma.label': 'Trauma & PTSD',
    'assessment.q1.trauma.desc': 'Past wounds, nervous system, safety',
    'assessment.q1.spiritual.label': 'Spiritual Alignment',
    'assessment.q1.spiritual.desc': 'Purpose, sacred connection, awakening',
    'assessment.q1.home.label': 'Home or Business Energy',
    'assessment.q1.home.desc': 'Space clearing, energy harmonization',
    'assessment.q2': 'How are you experiencing this in your body?',
    'assessment.q2.physical.label': 'Physical tension & pain',
    'assessment.q2.physical.desc': 'Tight shoulders, headaches, fatigue',
    'assessment.q2.emotional.label': 'Emotional heaviness',
    'assessment.q2.emotional.desc': 'Feeling stuck, numb, or overwhelmed',
    'assessment.q2.mental.label': 'Mental overdrive',
    'assessment.q2.mental.desc': 'Overthinking, difficulty concentrating',
    'assessment.q2.energetic.label': 'Energetic depletion',
    'assessment.q2.energetic.desc': 'Low vitality, disconnection from self',
    'assessment.q3': 'What kind of support resonates with you?',
    'assessment.q3.hands_on.label': 'Hands-on healing',
    'assessment.q3.hands_on.desc': 'Touch-based energy work and body therapies',
    'assessment.q3.sound.label': 'Sound & vibration',
    'assessment.q3.sound.desc': 'Healing through frequency and resonance',
    'assessment.q3.group.label': 'Community & sisterhood',
    'assessment.q3.group.desc': 'Shared healing in sacred women\'s circles',
    'assessment.q3.space.label': 'Space & environment',
    'assessment.q3.space.desc': 'Harmonizing physical and energetic spaces',
    'assessment.result.label': 'Your Recommendation',
    'assessment.book': 'Book This Session',
    'assessment.restart': 'Start Over',
    'assessment.back': 'Back',
    'assessment.continue': 'Continue',
    'assessment.see': 'See My Recommendation',
    'assessment.rec.access-bars.name': 'Access Bars',
    'assessment.rec.access-bars.desc': 'Based on what you shared, Access Bars is your ideal starting point. This hands-on technique gently dissolves the electromagnetic charge of anxious thoughts, limiting beliefs, and mental tension — creating space for ease, clarity, and deep nervous-system rest.',
    'assessment.rec.sound-bath.name': 'Sound Bath',
    'assessment.rec.sound-bath.desc': 'Your answers point toward the healing power of sound. Alchemical crystal singing bowls work directly with the body\'s energy field, releasing grief, emotional weight, and stress through pure vibrational frequency — no mental effort required.',
    'assessment.rec.karnak-pendulum.name': 'Karnak Pendulum Cleansing',
    'assessment.rec.karnak-pendulum.desc': 'Your responses indicate a need for deep energetic clearing — whether of a space, a recurring pattern, or an accumulated emotional charge. The Karnak Pendulum works at the root of the energy field, removing blockages and restoring internal balance from a distance.',
    'assessment.rec.womens-circle.name': "Women's Circle",
    'assessment.rec.womens-circle.desc': 'What you are moving through calls for shared healing. The Women\'s Circle is a sacred container where authentic sharing, collective wisdom, and witnessed vulnerability activate transformation that solo work cannot reach.',
    'assessment.rec.sacred-geometry.name': 'Sacred Geometry Harmonization',
    'assessment.rec.sacred-geometry.desc': 'Your path points toward deep energetic re-ordering. Sacred Geometry works with the five Platonic Solids to restructure your energy field from the inside out — restoring inner coherence, spiritual alignment, and a renewed sense of purpose.',
    'assessment.modality.inperson': 'In-Person',
    'assessment.modality.hybrid': 'Hybrid',
    'assessment.modality.remote': 'Remote or In-Person',

    'services.label': 'Healing Modalities',
    'services.title.1': 'The',
    'services.title.2': 'Therapies',
    'services.subtitle': 'Each session is designed to support your emotional, energetic, and spiritual well-being in a safe and intentional space.',
    'services.inperson': 'In-Person',
    'services.online': 'Online Available',
    'services.hybrid': 'Hybrid',
    'services.book': 'Book Session',
    'services.s1.name': 'Access Bars',
    'services.s1.desc': 'A gentle hands-on technique that releases the electromagnetic charge of limiting thoughts, beliefs, and emotions — creating space for deeper ease and clarity.',
    'services.s2.name': 'Sound Bath',
    'services.s2.desc': 'A Sound Bath with alchemical crystal singing bowls is a deep vibrational experience that uses pure sound frequencies as a tool for harmonizing the body, mind, and energetic field, promoting natural self-healing processes. Through the resonance of alchemical crystal bowls, an enveloping sound field is created that interacts directly with the energetic system, supporting the release of tension, internal reorganization, and the restoration of balance. Each bowl emits a specific frequency that acts on different levels of being, helping to relax mental activity, release accumulated tension in the physical body, and facilitate the natural flow of energy. These vibrations allow the nervous system to enter a state of greater calm, supporting self-regulation, deep rest, and the restoration of inner balance. On an energetic level, sound acts as a stimulus for coherence, helping to reorder patterns of tension, release emotional charge, and promote greater clarity and inner stability. It is an experience lived through the body, through vibration, rather than through the mind. Recommended for those seeking to reduce stress, release emotional weight, improve their inner connection, and reconnect with their natural capacity for self-healing.',
    'services.s3.name': 'Karnak Pendulum Cleansing',
    'services.s3.desc': 'Karnak Pendulum healing is a remote energetic session focused on the deep cleansing and harmonization of the energy field, releasing blockages and restoring internal balance in a holistic way. The session works on chakra harmonization and the integration of the four energetic bodies (physical, emotional, mental, and spiritual), promoting a sense of greater inner order, clarity, and stability. At the beginning and end of the session, a biometer measurement is taken, allowing precise observation of the energetic state before and after, making the changes in the energy field visible. This work is oriented toward people who feel energetic fatigue, emotional overload, internal disconnection, or the need to return to their center. It is a deep process of energetic cleansing and reorganization that allows you to recover lightness, focus, and overall well-being. Upon completion, an audio feedback recording is delivered with details of the work done, the findings in the energy field, and recommendations for integrating the process.',
    'services.s3.sub1': 'Homes & Spaces',
    'services.s3.sub2': 'Business Locations',
    'services.s3.sub3': 'Energetic Potentialization',
    'services.s4.name': "Women's Circle",
    'services.s4.desc': 'A sacred space where women gather to share, heal, and celebrate together. Guided rituals, authentic connection, and collective wisdom activate healing beyond the individual.',
    'services.s5.name': 'Sacred Geometry Harmonization',
    'services.s5.desc': 'A personalized energetic activation that works with the Platonic Solids — five geometric forms considered the fundamental patterns underlying the structure of all creation. Each of these figures holds a specific energetic frequency that interacts with the energy field in a distinct way: some support grounding and stability, others facilitate emotional release, mental clarity, expanded perception, or deep inner connection. In each session, the Platonic Solids are individually selected according to what the person needs to work on, allowing sacred geometry to act as a resource for reorganizing and harmonizing the energetic system. Through guided visualization and conscious energetic work, blockages are released and states of greater inner coherence are integrated.',
    'services.modality.inperson': 'In-Person',
    'services.modality.remote': 'Remote or In-Person',
    'services.modality.remoteonly': 'Remote Only',
    'services.s1.price': '$60',
    'services.s2.price': '$40 online · $60 in-person',
    'services.s3.price': '$40',
    'services.s4.price': '$25',
    'services.s5.price': '$40',
    'services.s6.name': 'Group Sound Bath Online',
    'services.s6.desc': 'A live group sound bath experience with alchemical crystal singing bowls, held online. Join from anywhere and immerse yourself in pure vibrational frequencies that release stress, emotional weight, and mental tension — all from the comfort of your own space. Perfect for those new to sound healing or looking for an accessible, collective healing experience.',
    'services.s6.price': '$25',

    'testimonials.label': 'Client Stories',
    'testimonials.title.1': 'Voices of',
    'testimonials.title.2': 'Transformation',
    'testimonials.t1.quote': 'After my first Access Bars session with Maca, I felt lighter than I had in years. It was as if the constant noise in my head simply... stopped. I left feeling peaceful and surprisingly clear about what I wanted for my life.',
    'testimonials.t1.name': 'Valentina M.',
    'testimonials.t1.location': 'Calgary, Canada',
    'testimonials.t2.quote': 'I was skeptical about doing a Sound Bath session remotely, but the experience was absolutely profound. Maca created such a sacred container — I cried, I released, and I felt truly held throughout the entire journey.',
    'testimonials.t2.name': 'Laura P.',
    'testimonials.t2.location': 'Online',
    'testimonials.t3.quote': "The Women's Circle changed something fundamental in me. There's a kind of healing that only happens in the presence of other women — when we witness each other's truth. Maca holds that space with so much grace.",
    'testimonials.t3.name': 'Daniela R.',
    'testimonials.t3.location': "Women's Circle",
    'testimonials.t4.quote': 'I had Maca do an energetic cleansing on my new business space and the shift was immediate. The atmosphere felt completely different — lighter, more aligned. We signed three new contracts that same month.',
    'testimonials.t4.name': 'Carolina S.',
    'testimonials.t4.location': 'Remote Session',
    'testimonials.t5.quote': 'Working with sacred geometry through Maca awakened something ancient in me. I understand now that healing isn\'t just about removing pain — it\'s about returning to your true design. Deeply recommended.',
    'testimonials.t5.name': 'Florencia T.',
    'testimonials.t5.location': 'Mendoza',

    'faq.label': 'Questions & Answers',
    'faq.title.1': 'Frequently',
    'faq.title.2': 'Asked',
    'faq.q1': 'Do I need any previous experience with holistic therapies?',
    'faq.a1': 'Not at all. All sessions are designed to welcome you exactly where you are. Whether this is your first experience with energy healing or you have been on this path for years, each session is tailored to your individual needs.',
    'faq.q2': 'How do online sessions work?',
    'faq.a2': 'Online sessions are held via Zoom or WhatsApp video. Energy healing works beyond physical distance — what matters is your intention and openness. Before your session, I ask you to be in a quiet, comfortable space. I guide you through a grounding practice and we begin. Most clients report experiences just as deep as in-person.',
    'faq.q3': 'How many sessions do I need?',
    'faq.a3': 'Every body and every journey is different. Many people feel a significant shift after just one session. For deeper or long-standing patterns, a series of 3–5 sessions is often recommended. We assess together at the end of each session and I never push more than what genuinely serves you.',
    'faq.q4': 'What is the difference between Access Bars and energetic harmonization?',
    'faq.a4': 'Access Bars involves gentle touch on 32 specific points on the head to release the electromagnetic charge of stored thoughts and beliefs — it\'s deeply relaxing and works with the mind. Energetic harmonization uses sacred geometry and the Karnak pendulum to work with the energetic field of your body or space, addressing energetic blockages and imbalances at a structural level.',
    'faq.q5': 'How do I prepare for my session?',
    'faq.a5': 'Wear comfortable clothing and avoid heavy meals or alcohol beforehand. Come with an open intention — even if it\'s simply "I want to feel better." For online sessions, find a quiet, private space and have a blanket nearby. For in-person sessions, arrive a few minutes early to settle in. After your session, drink plenty of water and give yourself time to rest.',
    'faq.q6': 'What is your cancellation and rescheduling policy?',
    'faq.a6': 'I kindly ask for at least 24 hours notice for cancellations or rescheduling. Sessions cancelled with less than 24 hours notice may forfeit the deposit. I always try to be flexible — life happens — so if something comes up, please reach out and we will find a solution together.',
    'faq.cta.title': 'Still have questions?',
    'faq.cta.desc': "I'm happy to connect before you book. Reach out and let's talk.",
    'faq.cta.btn': 'Get in Touch',

    'instagram.label': 'Follow the Journey',
    'instagram.subtitle': 'Daily doses of healing wisdom, sacred practices, and soul medicine.',
    'instagram.preview': 'Preview — connect Behold to display real posts from @expansion_holistiica',
    'instagram.btn': 'View on Instagram',

    'booking.label': 'Reservations',
    'booking.title': 'Ready to begin\nyour journey?',
    'booking.title.1': 'Book a',
    'booking.title.2': 'Session',
    'booking.subtitle': 'Choose your session and take the first step toward transformation.',
    'booking.name': 'Full Name',
    'booking.email': 'Email Address',
    'booking.service': 'Choose a Service',
    'booking.date': 'Preferred Date',
    'booking.message': 'Message (optional)',
    'booking.message.placeholder': 'Share anything that feels relevant — intentions, questions, or what brings you here...',
    'booking.submit': 'Request Booking',
    'booking.success': 'Your booking request has been sent. I\'ll be in touch within 24 hours.',
    'booking.select.session': 'Select Your Session',
    'booking.choose.therapy': 'Choose a Therapy',
    'booking.select.placeholder': 'Select a therapy...',
    'therapy.access-bars': 'Access Bars',
    'therapy.sound-bath': 'Sound Bath',
    'therapy.sound-bath-group': 'Group Sound Bath Online',
    'therapy.karnak-pendulum': 'Karnak Pendulum Cleansing',
    'therapy.womens-circle': "Women's Circle",
    'therapy.sacred-geometry': 'Sacred Geometry Harmonization',
    'booking.session.format': 'Session Format',
    'booking.inperson.only': 'This therapy is a hands-on technique available in-person only.',
    'booking.online.only': 'This therapy is available remotely only.',
    'booking.pay.cta': 'Pay & Reserve Session',
    'booking.link.soon': 'Payment link coming soon.',
    'booking.stripe.note': "Secure payment via Stripe — you'll receive a confirmation email",
    'booking.good.to.know': 'Good to Know',
    'booking.online.title': 'Online Sessions Available',
    'booking.online.desc': 'Most therapies can be experienced remotely with the same depth and effectiveness as in-person.',
    'booking.inperson.title': 'In-Person Sessions',
    'booking.inperson.desc': 'Access Bars is available in-person only.',
    'booking.scheduling.title': 'Flexible Scheduling',
    'booking.scheduling.desc': 'Sessions available on weekdays and weekends. Contact me to check availability.',
    'booking.payments.title': 'Payments & Cancellations',
    'booking.payments.desc': 'Payment is processed securely via Stripe. Please reach out for cancellation policy details.',
    'booking.unsure': 'Not sure which session is right for you?',
    'booking.assessment.cta': 'Take the Free Assessment',
    'booking.choose.date': 'Choose a Date',

    'footer.tagline': 'Sacred healing for the modern soul.',
    'footer.nav': 'Navigation',
    'footer.connect': 'Connect',
    'footer.rights': 'All rights reserved.',
    'footer.connect.email': 'Email',
    'footer.connect.whatsapp': 'WhatsApp',
    'footer.connect.instagram': 'Instagram',
    'footer.subtitle': 'Holistic Therapist',
    'footer.desc': 'Guiding holistic healing experiences that restore balance, calm the mind, and reconnect body, energy, and spirit.',
    'footer.quote': 'Every healing journey begins with a single courageous step.',
    'footer.quote.attr': '– Holistic Therapist',
    'footer.made': 'Made with',
    'footer.made.for': 'for healing and transformation',
    'footer.back.top': 'Back to Top',

    'navbar.subtitle': 'Holistic Therapist',

    'services.see.less': '— See less',
    'services.see.more': '+ See more',

    'floating.mute': 'Mute ambient sound',
    'floating.play': 'Play ambient sound',
    'floating.top': 'Back to top',
    'floating.whatsapp': 'Message me on WhatsApp',
    'floating.book': 'Book Now',

    'chat.badge': 'Chat with Luz ✨',
    'chat.open': 'Open chat',
    'chat.subtitle': 'Virtual assistant · Maca Salvo',
    'chat.placeholder': 'Write a message…',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.assessment': 'Evaluación',
    'nav.services': 'Servicios',
    'nav.instagram': 'Instagram',
    'nav.booking': 'Reservas',
    'nav.contact': 'Contacto',
    'nav.cta': 'Reservar Sesión',

    'hero.subtitle': 'Terapeuta Holística',
    'hero.tagline': 'Expande tu energía.\nSana tus raíces.\nVive plenamente.',
    'hero.badge': 'Sanación Holística',
    'hero.h1.1': 'Restaura Tu',
    'hero.h1.accent': 'Equilibrio',
    'hero.h1.2': 'Cuerpo, Energía y Espíritu',
    'hero.quote': 'La sanación es un camino, no un destino.',
    'hero.description': 'Sonido sagrado, trabajo energético y sanación intuitiva para restaurar el equilibrio y despertar tu máximo potencial.',
    'hero.cta.primary': 'Comienza Tu Camino',
    'hero.cta.secondary': 'Ver Servicios',
    'hero.scroll': 'Desliza para explorar',

    'about.label': 'La Sanadora',
    'about.meet': 'Conoce a',
    'about.title': 'Una guía de regreso\na ti misma',
    'about.p1': 'Soy Maca Salvo — terapeuta holística que combina sabiduría ancestral con prácticas energéticas modernas para apoyar transformaciones profundas.',
    'about.p2': 'Mi camino comenzó con mi propio proceso de sanación, navegando la ansiedad, la desconexión y la búsqueda de un significado más profundo. Ese camino me llevó a descubrir el poder del sonido, la energía y el ritual sagrado.',
    'about.p3': 'Hoy sostengo el espacio para quienes están listos para quitar las capas — reconectarse con la inteligencia del cuerpo, soltar lo que ya no sirve y dar el paso a su expresión más plena.',
    'about.certifications': 'Certificaciones y Formación',
    'about.cert1': 'Practicante Certificada de Sanación con Sonido',
    'about.cert2': 'Facilitadora de Access Bars',
    'about.cert3': 'Geometría Sagrada y Péndulo Karnak',
    'about.cert4': 'Maestra Reiki Nivel III',
    'about.cert5': 'Practicante de Theta Healing',
    'about.cta': 'Agendar una Sesión',
    'about.stat1.value': '500+',
    'about.stat1.label': 'Vidas Tocadas',
    'about.stat2.value': '8+',
    'about.stat2.label': 'Años de Práctica',
    'about.stat3.value': '12',
    'about.stat3.label': 'Modalidades',
    'about.journey.label': 'Mi Camino',
    'about.journey.title': 'Un Camino de Despertar',
    'about.journey.text': 'Todo comenzó con una inquietud silenciosa — la sensación de que había algo más profundo esperando ser encontrado. Esa intuición se convirtió en el inicio de todo.\n\nMe sumergí en terapias holísticas y prácticas energéticas, no como estudiante, sino como alguien buscándose a sí misma. Cada herramienta que encontré dejó una huella.\n\nMe formé y certifiqué como terapeuta holística para ofrecer lo que transformó mi propia vida: un espacio amoroso y consciente para sanar.\n\nHoy camino junto a otros en su proceso — ayudándoles a soltar, a reencontrar su centro y a reconectar con la sabiduría que siempre llevaron dentro.',
    'about.philosophy.label': 'Mi Filosofía',
    'about.philosophy.title': 'La vida como un proceso de expansión y reconexión',
    'about.philosophy.text': 'Creo en un camino de vida consciente, donde cada experiencia tiene un propósito y nos invita a volver a nosotros mismos.\n\nPara mí, la sanación no es un destino, sino un proceso de reconexión constante con el cuerpo, la mente, la energía y la esencia. Un recordar quiénes somos más allá de lo aprendido, lo condicionado y lo que hemos sostenido por años.\n\nTrabajo desde la idea de que todo está en constante movimiento: nuestras emociones, nuestra energía y nuestra vibración. Cuando aprendemos a observarnos con presencia y amor, comenzamos a generar espacios internos de equilibrio y transformación real.\n\nCreo profundamente en la inteligencia del cuerpo y en la sabiduría interna que cada persona tiene para guiar su propio proceso. Mi rol es acompañar, sostener y facilitar espacios donde eso pueda emerger con mayor claridad.\n\nCada encuentro es una invitación a volver a la coherencia interna, a soltar lo que pesa y a abrir espacio para una versión más alineada y consciente de uno mismo.\n\nTambién creo que la sanación no es lineal — tiene su propio ritmo, sus pausas y sus saltos hacia adelante. Honrar ese proceso, sin forzarlo, es el corazón de todo lo que hago.',
    'about.approach.label': 'Mi Enfoque',
    'about.approach.title': 'Un Espacio Intencional y Personalizado',
    'about.explore': 'Explorar Mis Servicios',
    'about.years': 'Años',
    'about.value1.label': 'Compasión',
    'about.value1.desc': 'Cada sesión comienza con una escucha profunda y un corazón abierto.',
    'about.value2.label': 'Sanación Natural',
    'about.value2.desc': 'Aprovechando la sabiduría ancestral y las prácticas energéticas naturales.',
    'about.value3.label': 'Espacio Sagrado',
    'about.value3.desc': 'Creando entornos intencionales para que la transformación se despliege.',
    'about.value4.label': 'Empoderamiento',
    'about.value4.desc': 'Guiándote a redescubrir tu propia luz interior y tu fortaleza.',

    'assessment.label': 'Autodescubrimiento',
    'assessment.title': '¿Por dónde comienza\ntu sanación?',
    'assessment.subtitle': 'Responde unas preguntas para descubrir qué modalidad de sanación se alinea más con tus necesidades actuales.',
    'assessment.step': 'Paso',
    'assessment.of': 'de',
    'assessment.complete': '% Completado',
    'assessment.q1': '¿En qué podemos ayudarte?',
    'assessment.q1.anxiety.label': 'Ansiedad',
    'assessment.q1.anxiety.desc': 'Preocupación constante, pensamientos acelerados, tensión',
    'assessment.q1.depression.label': 'Depresión',
    'assessment.q1.depression.desc': 'Bajo estado de ánimo, falta de motivación, vacío',
    'assessment.q1.relationships.label': 'Vínculos y Relaciones',
    'assessment.q1.relationships.desc': 'Patrones, comunicación, conexión',
    'assessment.q1.transitions.label': 'Transiciones Vitales',
    'assessment.q1.transitions.desc': 'Grandes cambios, nuevos capítulos, incertidumbre',
    'assessment.q1.grief.label': 'Duelo y Pérdida',
    'assessment.q1.grief.desc': 'Procesar finales, duelo, aceptación',
    'assessment.q1.stress.label': 'Manejo del Estrés',
    'assessment.q1.stress.desc': 'Agobio, burnout, agotamiento',
    'assessment.q1.selfesteem.label': 'Autoestima',
    'assessment.q1.selfesteem.desc': 'Autoestima, confianza, voz interior',
    'assessment.q1.trauma.label': 'Trauma y TEPT',
    'assessment.q1.trauma.desc': 'Heridas del pasado, sistema nervioso, seguridad',
    'assessment.q1.spiritual.label': 'Alineación Espiritual',
    'assessment.q1.spiritual.desc': 'Propósito, conexión sagrada, despertar',
    'assessment.q1.home.label': 'Energía del Hogar o Negocio',
    'assessment.q1.home.desc': 'Limpieza de espacios, armonización energética',
    'assessment.q2': '¿Cómo lo estás viviendo en tu cuerpo?',
    'assessment.q2.physical.label': 'Tensión y dolor físico',
    'assessment.q2.physical.desc': 'Hombros tensos, dolores de cabeza, fatiga',
    'assessment.q2.emotional.label': 'Peso emocional',
    'assessment.q2.emotional.desc': 'Sensación de bloqueo, entumecimiento o agobio',
    'assessment.q2.mental.label': 'Mente en sobremarcha',
    'assessment.q2.mental.desc': 'Sobreanálisis, dificultad para concentrarse',
    'assessment.q2.energetic.label': 'Agotamiento energético',
    'assessment.q2.energetic.desc': 'Poca vitalidad, desconexión de uno mismo',
    'assessment.q3': '¿Qué tipo de apoyo resuena contigo?',
    'assessment.q3.hands_on.label': 'Sanación con las manos',
    'assessment.q3.hands_on.desc': 'Trabajo energético táctil y terapias corporales',
    'assessment.q3.sound.label': 'Sonido y vibración',
    'assessment.q3.sound.desc': 'Sanación a través de frecuencia y resonancia',
    'assessment.q3.group.label': 'Comunidad y sororidad',
    'assessment.q3.group.desc': 'Sanación compartida en círculos sagrados de mujeres',
    'assessment.q3.space.label': 'Espacio y entorno',
    'assessment.q3.space.desc': 'Armonización de espacios físicos y energéticos',
    'assessment.result.label': 'Tu Camino Recomendado',
    'assessment.book': 'Reservar Esta Sesión',
    'assessment.restart': 'Volver a Empezar',
    'assessment.back': 'Atrás',
    'assessment.continue': 'Continuar',
    'assessment.see': 'Ver Mi Recomendación',
    'assessment.rec.access-bars.name': 'Access Bars',
    'assessment.rec.access-bars.desc': 'Según lo que compartiste, Access Bars es tu punto de partida ideal. Esta técnica con las manos disuelve suavemente la carga electromagnética de pensamientos ansiosos, creencias limitantes y tensión mental — creando espacio para la facilidad, la claridad y un descanso profundo del sistema nervioso.',
    'assessment.rec.sound-bath.name': 'Baño de Sonido',
    'assessment.rec.sound-bath.desc': 'Tus respuestas apuntan al poder sanador del sonido. Los cuencos alquímicos de cristal trabajan directamente con el campo energético del cuerpo, liberando duelo, peso emocional y estrés a través de la frecuencia vibracional pura — sin esfuerzo mental.',
    'assessment.rec.karnak-pendulum.name': 'Limpieza con Péndulo Karnak',
    'assessment.rec.karnak-pendulum.desc': 'Tus respuestas indican una necesidad de limpieza energética profunda — ya sea de un espacio, un patrón recurrente o una carga emocional acumulada. El Péndulo Karnak actúa en la raíz del campo energético, removiendo bloqueos y restaurando el equilibrio interno desde la distancia.',
    'assessment.rec.womens-circle.name': 'Círculo de Mujeres',
    'assessment.rec.womens-circle.desc': 'Lo que estás atravesando pide una sanación compartida. El Círculo de Mujeres es un contenedor sagrado donde el compartir auténtico, la sabiduría colectiva y la vulnerabilidad testimoniada activan transformaciones que el trabajo individual no puede alcanzar.',
    'assessment.rec.sacred-geometry.name': 'Armonización con Geometría Sagrada',
    'assessment.rec.sacred-geometry.desc': 'Tu camino apunta hacia una reordenación energética profunda. La Geometría Sagrada trabaja con los cinco Sólidos Platónicos para reestructurar tu campo energético desde adentro hacia afuera — restaurando la coherencia interior, la alineación espiritual y un renovado sentido de propósito.',
    'assessment.modality.inperson': 'Presencial',
    'assessment.modality.hybrid': 'Híbrido',
    'assessment.modality.remote': 'Remoto o Presencial',

    'services.label': 'Modalidades de Sanación',
    'services.title.1': 'Las',
    'services.title.2': 'Terapias',
    'services.subtitle': 'Cada sesión está diseñada para apoyar tu bienestar emocional, energético y espiritual en un espacio seguro e intencional.',
    'services.inperson': 'Presencial',
    'services.online': 'Disponible Online',
    'services.hybrid': 'Híbrido',
    'services.book': 'Reservar Sesión',
    'services.s1.name': 'Access Bars',
    'services.s1.desc': 'Una técnica suave con las manos que libera la carga electromagnética de pensamientos, creencias y emociones limitantes — creando espacio para mayor facilidad y claridad.',
    'services.s2.name': 'Baño de Sonido',
    'services.s2.desc': 'El baño de sonido con cuencos alquímicos de cristal es una experiencia vibracional profunda que utiliza frecuencias puras de sonido como herramienta de armonización del cuerpo, la mente y el campo energético, promoviendo procesos naturales de autosanación. A través de la resonancia de los cuencos de cristal alquímico, se genera un campo sonoro envolvente que interactúa directamente con el sistema energético, favoreciendo la liberación de tensiones, la reorganización interna y el restablecimiento del equilibrio. Cada cuenco emite una frecuencia específica que actúa sobre distintos niveles del ser, ayudando a relajar la actividad mental, liberar tensiones acumuladas en el cuerpo físico y facilitar la circulación natural de la energía. Estas vibraciones permiten que el sistema nervioso entre en un estado de mayor calma, lo que favorece la autorregulación, el descanso profundo y la restauración del equilibrio interno. A nivel energético, el sonido actúa como un estímulo de coherencia, ayudando a ordenar patrones de tensión, soltar carga emocional y promover mayor claridad y estabilidad interna. Es una experiencia que se vive desde el cuerpo, a través de la vibración, más que desde la mente. Es una experiencia recomendada para personas que buscan reducir estrés, liberar carga emocional, mejorar su conexión interna y reconectar con su capacidad natural de autosanación.',
    'services.s3.name': 'Limpieza con Péndulo Karnak',
    'services.s3.desc': 'La sanación con Péndulo de Karnak es una sesión energética a distancia enfocada en la limpieza y armonización profunda del campo energético, permitiendo liberar bloqueos y restablecer el equilibrio interno de forma integral. Durante la sesión se trabaja la armonización de los chakras y la integración de los cuatro cuerpos energéticos (físico, emocional, mental y espiritual), favoreciendo una sensación de mayor orden interno, claridad y estabilidad. Al inicio y al final se realiza una medición con biómetro, lo que permite observar con precisión el estado energético previo y posterior a la sesión, evidenciando los cambios en el campo energético. Este trabajo está orientado a personas que sienten cansancio energético, sobrecarga emocional, desconexión interna o la necesidad de volver a su centro. Es un proceso profundo de limpieza y reorganización energética que permite recuperar ligereza, enfoque y bienestar general. Al finalizar, se entrega un audio de devolución con el detalle de lo trabajado, los hallazgos del campo energético y recomendaciones para integrar el proceso.',
    'services.s3.sub1': 'Hogares y Espacios',
    'services.s3.sub2': 'Locales Comerciales',
    'services.s3.sub3': 'Potencialización Energética',
    'services.s4.name': 'Círculo de Mujeres',
    'services.s4.desc': 'Un espacio sagrado donde mujeres se reúnen para compartir, sanar y celebrar juntas. Rituales guiados, conexión auténtica y sabiduría colectiva activan la sanación más allá del individuo.',
    'services.s5.name': 'Armonización con Geometría Sagrada',
    'services.s5.desc': 'Es una activación energética personalizada que trabaja con los Sólidos Platónicos, cinco formas geométricas consideradas los patrones fundamentales de la estructura de la creación. Cada una de estas figuras contiene una frecuencia energética específica que interactúa con el campo energético de manera distinta: algunas favorecen el enraizamiento y la estabilidad, otras apoyan la liberación emocional, otras facilitan la claridad mental, la expansión de la percepción o la conexión interna. En esta sesión se seleccionan los Sólidos Platónicos de forma individual según lo que la persona necesita trabajar, permitiendo que la geometría sagrada actúe como un recurso de reorganización y armonización del sistema energético. A través de visualización guiada y trabajo energético consciente, se facilita la liberación de bloqueos y la integración de estados de mayor coherencia interna.',
    'services.modality.inperson': 'Presencial',
    'services.modality.remote': 'Remoto o Presencial',
    'services.modality.remoteonly': 'Solo a Distancia',
    'services.s1.price': '$60',
    'services.s2.price': '$40 online · $60 presencial',
    'services.s3.price': '$40',
    'services.s4.price': '$25',
    'services.s5.price': '$40',
    'services.s6.name': 'Baño de Sonido Grupal Online',
    'services.s6.desc': 'Una experiencia de baño de sonido grupal en vivo con cuencos alquímicos de cristal, realizada de forma online. Unite desde donde estés e inmergite en frecuencias vibracionales puras que liberan el estrés, el peso emocional y la tensión mental — desde la comodidad de tu espacio. Ideal para quienes se inician en la sanación con sonido o buscan una experiencia de sanación colectiva accesible.',
    'services.s6.price': '$25',

    'testimonials.label': 'Historias de Clientes',
    'testimonials.title.1': 'Voces de la',
    'testimonials.title.2': 'Transformación',
    'testimonials.t1.quote': 'Después de mi primera sesión de Access Bars con Maca, me sentí más liviana que en años. Era como si el ruido constante en mi cabeza simplemente... se detuviera. Salí sintiéndome en paz y con una claridad inesperada sobre lo que quería para mi vida.',
    'testimonials.t1.name': 'Valentina M.',
    'testimonials.t1.location': 'Calgary, Canada',
    'testimonials.t2.quote': 'Era escéptica respecto a hacer una sesión de Baño de Sonido de forma remota, pero la experiencia fue absolutamente profunda. Maca creó un contenedor tan sagrado — lloré, liberé, y me sentí verdaderamente sostenida durante todo el camino.',
    'testimonials.t2.name': 'Laura P.',
    'testimonials.t2.location': 'Online',
    'testimonials.t3.quote': 'El Círculo de Mujeres cambió algo fundamental en mí. Hay un tipo de sanación que solo ocurre en la presencia de otras mujeres — cuando nos somos testigos mutuamente de nuestra verdad. Maca sostiene ese espacio con mucha gracia.',
    'testimonials.t3.name': 'Daniela R.',
    'testimonials.t3.location': 'Círculo de Mujeres',
    'testimonials.t4.quote': 'Pedí a Maca que hiciera una limpieza energética en mi nuevo local de negocios y el cambio fue inmediato. La atmósfera se sentía completamente diferente — más liviana, más alineada. Firmamos tres nuevos contratos ese mismo mes.',
    'testimonials.t4.name': 'Carolina S.',
    'testimonials.t4.location': 'Sesión Remota',
    'testimonials.t5.quote': 'Trabajar con geometría sagrada a través de Maca despertó algo ancestral en mí. Entiendo ahora que sanar no es solo eliminar el dolor — es volver a tu diseño verdadero. Ampliamente recomendada.',
    'testimonials.t5.name': 'Florencia T.',
    'testimonials.t5.location': 'Mendoza',

    'faq.label': 'Preguntas Frecuentes',
    'faq.title.1': 'Preguntas',
    'faq.title.2': 'Frecuentes',
    'faq.q1': '¿Necesito experiencia previa con terapias holísticas?',
    'faq.a1': 'Para nada. Todas las sesiones están diseñadas para recibirte exactamente donde estás. Ya sea que esta sea tu primera experiencia con sanación energética o lleves años en este camino, cada sesión se adapta a tus necesidades individuales.',
    'faq.q2': '¿Cómo funcionan las sesiones online?',
    'faq.a2': 'Las sesiones online se realizan por Zoom o WhatsApp video. La sanación energética funciona más allá de la distancia física — lo que importa es tu intención y apertura. Antes de tu sesión, te pido que estés en un espacio tranquilo y cómodo. Te guío a través de una práctica de anclaje y comenzamos. La mayoría de los clientes reportan experiencias tan profundas como las presenciales.',
    'faq.q3': '¿Cuántas sesiones necesito?',
    'faq.a3': 'Cada cuerpo y cada camino es diferente. Muchas personas sienten un cambio significativo después de una sola sesión. Para patrones más profundos o de larga data, se suele recomendar una serie de 3 a 5 sesiones. Evaluamos juntos al final de cada sesión y nunca sugiero más de lo que genuinamente te sirve.',
    'faq.q4': '¿Cuál es la diferencia entre Access Bars y la armonización energética?',
    'faq.a4': 'Access Bars implica un toque suave en 32 puntos específicos de la cabeza para liberar la carga electromagnética de pensamientos y creencias almacenados — es profundamente relajante y trabaja con la mente. La armonización energética usa geometría sagrada y el péndulo Karnak para trabajar con el campo energético de tu cuerpo o espacio, abordando bloqueos e desequilibrios a nivel estructural.',
    'faq.q5': '¿Cómo me preparo para mi sesión?',
    'faq.a5': 'Usa ropa cómoda y evita comidas pesadas o alcohol antes de la sesión. Llega con una intención abierta — incluso si es simplemente "quiero sentirme mejor." Para sesiones online, encuentra un espacio tranquilo y privado y ten una manta cerca. Para sesiones presenciales, llega unos minutos antes para acomodarte. Después de la sesión, bebe mucha agua y date tiempo para descansar.',
    'faq.q6': '¿Cuál es tu política de cancelación y reprogramación?',
    'faq.a6': 'Solicito amablemente al menos 24 horas de aviso para cancelaciones o reprogramaciones. Las sesiones canceladas con menos de 24 horas pueden perder el depósito. Siempre trato de ser flexible — la vida sucede — así que si algo surge, contáctame y encontraremos una solución juntos.',
    'faq.cta.title': '¿Tienes más preguntas?',
    'faq.cta.desc': 'Me alegra conectar antes de que reserves. Escríbeme y hablamos.',
    'faq.cta.btn': 'Contactar',

    'instagram.label': 'Sigue el camino',
    'instagram.subtitle': 'Dosis diarias de sabiduría sanadora, prácticas sagradas y medicina del alma.',
    'instagram.preview': 'Vista previa — conecta Behold para mostrar los posts reales de @expansion_holistiica',
    'instagram.btn': 'Ver en Instagram',

    'booking.label': 'Reservas',
    'booking.title': '¿Lista para comenzar\ntu camino?',
    'booking.title.1': 'Reserva una',
    'booking.title.2': 'Sesión',
    'booking.subtitle': 'Elige tu sesión y da el primer paso hacia la transformación.',
    'booking.name': 'Nombre Completo',
    'booking.email': 'Correo Electrónico',
    'booking.service': 'Elige un Servicio',
    'booking.date': 'Fecha Preferida',
    'booking.message': 'Mensaje (opcional)',
    'booking.message.placeholder': 'Comparte lo que sientas relevante — intenciones, preguntas o qué te trae aquí...',
    'booking.submit': 'Solicitar Reserva',
    'booking.success': 'Tu solicitud de reserva fue enviada. Me pondré en contacto en menos de 24 horas.',
    'booking.select.session': 'Selecciona Tu Sesión',
    'booking.choose.therapy': 'Elige tu Terapia',
    'booking.select.placeholder': 'Selecciona una terapia...',
    'therapy.access-bars': 'Access Bars',
    'therapy.sound-bath': 'Baño de Sonido',
    'therapy.sound-bath-group': 'Baño de Sonido Grupal Online',
    'therapy.karnak-pendulum': 'Limpieza con Péndulo Karnak',
    'therapy.womens-circle': 'Círculo de Mujeres',
    'therapy.sacred-geometry': 'Armonización de Geometría Sagrada',
    'booking.session.format': 'Formato de Sesión',
    'booking.inperson.only': 'Esta terapia es una técnica presencial y solo está disponible de forma presencial.',
    'booking.online.only': 'Esta terapia está disponible únicamente de forma remota.',
    'booking.pay.cta': 'Pagar y Reservar Sesión',
    'booking.link.soon': 'Enlace de pago próximamente.',
    'booking.stripe.note': 'Pago seguro vía Stripe — recibirás un correo de confirmación',
    'booking.good.to.know': 'Información Útil',
    'booking.online.title': 'Sesiones Online Disponibles',
    'booking.online.desc': 'La mayoría de las terapias se pueden vivir de forma remota con la misma profundidad y efectividad que de manera presencial.',
    'booking.inperson.title': 'Sesiones Presenciales',
    'booking.inperson.desc': 'Access Bars está disponible solo de forma presencial.',
    'booking.scheduling.title': 'Horarios Flexibles',
    'booking.scheduling.desc': 'Sesiones disponibles entre semana y fines de semana. Contáctame para consultar disponibilidad.',
    'booking.payments.title': 'Pagos y Cancelaciones',
    'booking.payments.desc': 'El pago se procesa de forma segura a través de Stripe. Escríbeme para conocer la política de cancelación.',
    'booking.unsure': '¿No sabes qué sesión es para ti?',
    'booking.assessment.cta': 'Haz la Evaluación Gratuita',
    'booking.choose.date': 'Elige una Fecha',

    'footer.tagline': 'Sanación sagrada para el alma moderna.',
    'footer.nav': 'Navegación',
    'footer.connect': 'Conectar',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.connect.email': 'Email',
    'footer.connect.whatsapp': 'WhatsApp',
    'footer.connect.instagram': 'Instagram',
    'footer.subtitle': 'Terapeuta Holística',
    'footer.desc': 'Guiando experiencias de sanación holística que restauran el equilibrio, calman la mente y reconectan cuerpo, energía y espíritu.',
    'footer.quote': 'Todo camino de sanación comienza con un solo paso valiente.',
    'footer.quote.attr': '– Terapeuta Holística',
    'footer.made': 'Hecho con',
    'footer.made.for': 'para la sanación y la transformación',
    'footer.back.top': 'Volver Arriba',

    'navbar.subtitle': 'Terapeuta Holística',

    'services.see.less': '— Ver menos',
    'services.see.more': '+ Ver más',

    'floating.mute': 'Silenciar sonido ambiente',
    'floating.play': 'Reproducir sonido ambiente',
    'floating.top': 'Volver arriba',
    'floating.whatsapp': 'Escríbeme por WhatsApp',
    'floating.book': 'Reservar',

    'chat.badge': 'Chatea con Luz ✨',
    'chat.open': 'Abrir chat',
    'chat.subtitle': 'Asistente virtual · Maca Salvo',
    'chat.placeholder': 'Escribe un mensaje…',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'es',
  setLang: () => {},
  t: (k) => k,
});

// Spanish (Chile) is served at "/", English (Canada) at "/en/".
// Deriving the language from the URL gives each language its own indexable URL.
function getLangFromPath(): Lang {
  if (typeof window === 'undefined') return 'es';
  const segments = window.location.pathname.split('/').filter(Boolean);
  return segments.includes('en') ? 'en' : 'es';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(getLangFromPath);

  useEffect(() => {
    document.documentElement.lang = lang === 'en' ? 'en-CA' : 'es-CL';
  }, [lang]);

  useEffect(() => {
    const onPop = () => setLangState(getLangFromPath());
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof window !== 'undefined') {
      const target = l === 'en' ? '/en/' : '/';
      if (window.location.pathname !== target) {
        window.history.pushState({}, '', target);
      }
    }
  };

  const t = (key: string) => translations[lang][key] ?? translations['en'][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
